### ISSUE TITLE
Deteriorating WoodLogs won't join brand new ones

### ISSUE THREAD

**Issue by lisanhu** [emipa606/QuantumStorageRedux#1]
Thanks for maintaining this great Mod.

I'm finding the deteriorated woodlogs won't join the new ones in this mod, and in the default game, the pawns will pick up the deteriorated ones and join them to the non-deteriorated ones. Do you mind taking a look at it and deciding whether to fix it?

Thanks a lot!

**Comment by lisanhu** [comment]
Sorry, I forgot I prepared a save for you to test it out.
Here it is.

[test2.zip](https://github.com/emipa606/QuantumStorageRedux/files/12373903/test2.zip)

**Comment by emipa606** [comment]
Sorry, looked over the code but cant find what causes the issue. Its too convoluted for me I'm afraid.
